apiVersion: v1
kind: Service
metadata:
  name: ang-test-service
  namespace: ai-workloads
spec:
  selector:
    app: ang-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP